spring:
  application:
    name: dacrew-shell
  shell:
    interactive:
      enabled: true
  main:
    web-application-type: none
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
  rabbitmq:
    listener:
      simple:
        auto-startup: false

embabel:
  models:
    defaultLlm: llama3:latest

  agent-platform:
    ranking:
      llm: llama3:latest

  llms:
    llama3:latest:
      provider: ollama
      model: llama3:latest
      temperature: 0.7

    llama3.3:latest:
      provider: ollama
      model: llama3.3:latest
      temperature: 0.7

app:
  jira:
    base-url: https://karakun-agent.atlassian.net/
    auth-token: ${JIRA_TOKEN:}
    dry-run: true
    max-comment-length: 1024

logging:
  level:
    com.embabel: INFO
    com.embabel.agent.api.annotation.support.AgentMetadataReader: INFO
    org.dacrewj.agent: DEBUG
