spring:
  application:
    name: dacrew-shell
  shell:
    interactive:
      enabled: true
  main:
    web-application-type: none
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
  rabbitmq:
    listener:
      simple:
        auto-startup: false

embabel:
  models:
    defaultLlm: llama3:latest

  agent-platform:
    ranking:
      llm: llama3:latest

  llms:
    llama3:latest:
      provider: ollama
      model: llama3:latest
      temperature: 0.7

    llama3.3:latest:
      provider: ollama
      model: llama3.3:latest
      temperature: 0.7

logging:
  level:
    com.embabel: INFO
    com.embabel.agent.api.annotation.support.AgentMetadataReader: INFO
    org.dacrewj.agent: DEBUG


dacrew:
  jira:
    base-url: https://karakun-agent.atlassian.net/
    auth-token: ${JIRA_TOKEN:}
    dry-run: true
    max-comment-length: 1024

  agents:
    requirement-reviewer:
      max-concurrency: 8

      llm:
        model: llama3.3:latest
        temperature: 0.7

      reviewer:
        role: Requirement Reviewer

        goal: >
          Review the draft requirement and provide comprehensive feedback in the form of a critique i.e. a list of 
          criticisms, a list of improvement suggestions, and a statement whether the draft requirement has been approved
          for development or rejected.
          Consider the inputs comprising a summary and a description of the draft requirement.

        backstory: >
          You are an experienced reviewer of software requirement specifications skilled in finding the most relevant 
          flaws in a draft software requirement.  
          You excel at providing feedback which is necessary for the requirement to be approved for further processing
          by the software development team.

